# Generated by Django 3.2.23 on 2024-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', "П'ятниця"), ('Saturday', 'Субота')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subgroup',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
    ]
