# Generated by Django 3.2.23 on 2024-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240412_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='numerator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.CharField(choices=[('чисельник', 'Чисельник'), ('знаменник', 'Знаменник')], max_length=10),
        ),
    ]
